language: python
services:
  - docker
before_install:
  - apt update && apt install flake8 vulture
jobs:
  include:
    - stage: check_code
      script: make lint
    - stage: check_code
      script: make deadcode