language: python
services:
  - docker
before_install:
  - sudo apt install flake8 vulture
addons:
  apt:
    update: true
jobs:
  include:
    - stage: check_code
      script: make lint
    - stage: check_code
      script: make deadcode